<?php
$amp_conf['AMPDBUSER'] = 'asteriskuser';
$amp_conf['AMPDBPASS'] = '385044c4053aa853e679';
$amp_conf['AMPDBHOST'] = 'localhost';
$amp_conf['AMPDBNAME'] = 'asterisk';
$amp_conf['AMPDBENGINE'] = 'mysql';
$amp_conf['datasource'] = '';
require_once('/var/www/html/admin/bootstrap.php');
